version: '3.3'

services:
  
  # --- Services ---
  notifications:
    build:
      context: .
      dockerfile: Notifications.Dockerfile
    networks:
      - internal-network
    ports:
      - "5004:5004"
      - "5005:5005"
    depends_on:
      - rabbitmq
      - postgres

  # --- Infrastructure ---
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    networks:
      - external-network
      - internal-network
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - external-network
      - internal-network
    ports:
      - "5432:5432"

  proxy:
    container_name: proxy
    restart: always
    build:
      context: .
      dockerfile: Proxy.Dockerfile
    ports:
      - '80:80'
    links:
      - notifications
    networks:
      - external-network
      - internal-network
    command: [ nginx, '-g', 'daemon off;' ]


networks:
  external-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true
