version: '3.3'

services:
  
  # --- Services ---
  accounts:
    build:
      context: .
      dockerfile: Accounts.Dockerfile
    networks:
      - unicorn-network
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
      - postgres

  approvals:
    build:
      context: .
      dockerfile: Approvals.Dockerfile
    networks:
      - unicorn-network
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
      - postgres

  notifications:
    build:
      context: .
      dockerfile: Notifications.Dockerfile
    networks:
      - unicorn-network
    ports:
      - "5003:80"
    depends_on:
      - rabbitmq
      - postgres

  # --- Infrastructure ---
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    networks:
      - unicorn-network
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - unicorn-network
    ports:
      - "5432:5432"

networks:
  unicorn-network:
    driver: bridge