const ActionTypes = {

  // Query notifications
  QUERY_NOTIFICATIONS: 'QUERY_NOTIFICATIONS',
  QUERY_NOTIFICATIONS_INIT: 'QUERY_NOTIFICATIONS_INIT',
  QUERY_NOTIFICATIONS_UPDATE: 'QUERY_NOTIFICATIONS_UPDATE',
  QUERY_NOTIFICATIONS_ERROR: 'QUERY_NOTIFICATIONS_ERROR',

  // Query multiple accounts
  QUERY_ACCOUNTS: 'QUERY_ACCOUNTS',
  QUERY_ACCOUNTS_INIT: 'QUERY_ACCOUNTS_INIT',
  QUERY_ACCOUNTS_UPDATE: 'QUERY_ACCOUNTS_UPDATE',
  QUERY_ACCOUNTS_ERROR: 'QUERY_ACCOUNTS_ERROR',

  // Get one account
  GET_ACCOUNT_DETAIL: 'GET_ACCOUNT_DETAIL',
  GET_ACCOUNT_DETAIL_SUCCESS: 'GET_ACCOUNT_DETAIL_SUCCESS',
  GET_ACCOUNT_DETAIL_ERROR: 'GET_ACCOUNT_DETAIL_ERROR',

  // Create new account
  ADD_ACCOUNT: 'ADD_ACCOUNT',

  // Log in
  LOG_IN: 'LOG_IN',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_ERROR: 'LOG_IN_ERROR',

  // Log out
  LOG_OUT: 'LOG_OUT',

  // User view settings
  UPDATE_VIEW_SETTINGS: "UPDATE_VIEW_SETTINGS",

  // Get one user
  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR',

};

export { ActionTypes };
