// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Billings.Persistence.Migrations
{
    [DbContext(typeof(BillingsContext))]
    internal class BillingsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Billings.Persistence.Entities.BillingEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<float>("Amount")
                    .HasColumnType("real");

                b.Property<bool>("Approved")
                    .HasColumnType("boolean");

                b.Property<DateTime>("Created")
                    .HasColumnType("timestamp without time zone");

                b.Property<bool>("Pending")
                    .HasColumnType("boolean");

                b.Property<string>("ProfileId")
                    .HasColumnType("text");

                b.Property<int>("SequentialNumber")
                    .HasColumnType("integer");

                b.Property<Guid>("TransactionId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("Updated")
                    .HasColumnType("timestamp without time zone");

                b.Property<int>("Version")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Billings");
            });
#pragma warning restore 612, 618
        }
    }
}