const ActionTypes = {

    // Query notifications
    QUERY_NOTIFICATIONS: 'QUERY_NOTIFICATIONS',
    QUERY_NOTIFICATIONS_SUCCESS: 'QUERY_NOTIFICATIONS_SUCCESS',
    QUERY_NOTIFICATIONS_ERROR: 'QUERY_NOTIFICATIONS_ERROR',

    // Query multiple accounts
    QUERY_ACCOUNTS: 'QUERY_ACCOUNTS',
    QUERY_ACCOUNTS_SUCCESS: 'QUERY_ACCOUNTS_SUCCESS',
    QUERY_ACCOUNTS_ERROR: 'QUERY_ACCOUNTS_ERROR',

    // Get one account
    GET_ACCOUNT_DETAIL: 'GET_ACCOUNT_DETAIL',
    GET_ACCOUNT_DETAIL_SUCCESS: 'GET_ACCOUNT_DETAIL_SUCCESS',
    GET_ACCOUNT_DETAIL_ERROR: 'GET_ACCOUNT_DETAIL_ERROR',

    // Create new account
    ADD_ACCOUNT: 'ADD_ACCOUNT',

    // User view settings
    UPDATE_VIEW_SETTINGS: "UPDATE_VIEW_SETTINGS",

};

export {ActionTypes};
