// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Accounts.Persistence.Migrations
{
    [DbContext(typeof(AccountsContext))]
    internal class AccountsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Accounts.Persistence.Entities.AccountEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<bool>("Approved")
                    .HasColumnType("boolean");

                b.Property<float>("Balance")
                    .HasColumnType("real");

                b.Property<DateTime>("Created")
                    .HasColumnType("timestamp without time zone");

                b.Property<int>("LastTransactionNumber")
                    .HasColumnType("integer");

                b.Property<bool>("Pending")
                    .HasColumnType("boolean");

                b.Property<string>("ProfileId")
                    .HasColumnType("text");

                b.Property<DateTime>("Updated")
                    .HasColumnType("timestamp without time zone");

                b.Property<int>("Version")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Accounts");
            });
#pragma warning restore 612, 618
        }
    }
}